### ISSUE TITLE
 How to set up using local LLM instead of LLM fromopenai

### ISSUE THREAD

**Issue by hanquanjushi** [KE7/scenarioNL#46]
I have to use the local model due to some reasons. However, readme does not mention how to adjust the configuration to call the local model. If you can tell me the method, I would be very grateful.

**Comment by KE7** [comment]
Hi. Thanks for your question. At the time of submission we used a separate "adapter" for local LLMs. This adapter unfortunately does not include all of the features such as constrained decoding. But since then, packages like vLLM and LiteLLM have come out as a way to substitute GPT models so you would only need to adjust the openai base endpoint to point to your local host.

**Comment by hanquanjushi** [comment]
Thank you for your reply! By adding the appropriate parameters and adding the local model link to the correct location, I have successfully configured it.
